<a href="https://colab.research.google.com/github/damiencrim/deep_learning_challenge/blob/main/Alphabet_Soup_Charity_Model_Optimize_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN'.
application_df.drop(columns=["EIN"],inplace=True)

In [ ]:
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
app_count = application_df.APPLICATION_TYPE.value_counts()
app_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
applications_type_to_replace = list(app_count[app_count <500].index)

# Replace in dataframe
for app in applications_type_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df.CLASSIFICATION.value_counts()
classification_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
classification_count_to_replace = list(classification_count[classification_count<1000].index)

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
print(classification_count >1)

C1000     True
C2000     True
C1200     True
C3000     True
C2100     True
         ...
C4120    False
C8210    False
C2561    False
C4500    False
C2150    False
Name: CLASSIFICATION, Length: 71, dtype: bool

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classification_count_to_replace = list(classification_count[classification_count<1000].index)

# Replace in dataframe
for cls in classification_count_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Choose NAME value counts for binning
name_count = application_df['NAME'].value_counts()
name_count

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of names to be replaced
names_to_replace = list(name_count[name_count< 100].index)

# Replace in dataframe
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(
        name, "Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                 25987
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
HONOR SOCIETY OF PHI KAPPA PHI                                          107
MONTANA 4-H FOUNDATION INC                                              107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
Name: NAME, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
app_dummied = pd.get_dummies(application_df)
app_dummied.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CIVITAN INTERNATIONAL,NAME_DEMOLAY INTERNATIONAL,NAME_FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA,NAME_HABITAT FOR HUMANITY INTERNATIONAL INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
app_dummied.drop("IS_SUCCESSFUL",1)

<ipython-input-15-a75712dcd952>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  app_dummied.drop("IS_SUCCESSFUL",1)

,STATUS,ASK_AMT,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CIVITAN INTERNATIONAL,NAME_DEMOLAY INTERNATIONAL,NAME_FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA,NAME_HABITAT FOR HUMANITY INTERNATIONAL INC,NAME_HONOR SOCIETY OF PHI KAPPA PHI,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
X = app_dummied.drop("IS_SUCCESSFUL", axis=1)
y = app_dummied.IS_SUCCESSFUL

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
X_train.head()

,STATUS,ASK_AMT,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CIVITAN INTERNATIONAL,NAME_DEMOLAY INTERNATIONAL,NAME_FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA,NAME_HABITAT FOR HUMANITY INTERNATIONAL INC,NAME_HONOR SOCIETY OF PHI KAPPA PHI,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
30531,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22775,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
19057,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
27536,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
21331,1,11121098,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0

In [ ]:
type(X_train.index)

pandas.core.indexes.numeric.Int64Index

## Compile, Train and Evaluate the Model

In [ ]:
!pip install pandas tensorflow

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.15.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.5.26)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (16.0.6)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.9.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.36.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.60.1)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.1)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.42.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.17.3)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (1.2.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.5.2)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.0.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (5.3.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2024.2.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow) (2.1.5)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.5.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (3.2.2)

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21
hidden_nodes_layer4=21
hidden_nodes_layer5=28

nn = tf.keras.models.Sequential()

nn = tf.keras.models.Sequential()

In [ ]:
# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation='tanh'))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation='linear'))

# Fifth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer5, activation='relu'))



# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 525

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 21)                315

 dense_3 (Dense)             (None, 21)                462

 dense_4 (Dense)             (None, 28)                616

 dense_5 (Dense)             (None, 1)                 29

=================================================================
Total params: 2059 (8.04 KB)
Trainable params: 2059 (8.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=200)

Epoch 1/100
684/684 [==============================] - 3s 3ms/step - loss: 0.5450 - accuracy: 0.7181 - val_loss: 0.5112 - val_accuracy: 0.7357
Epoch 2/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5024 - accuracy: 0.7477 - val_loss: 0.5012 - val_accuracy: 0.7432
Epoch 3/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4973 - accuracy: 0.7506 - val_loss: 0.5015 - val_accuracy: 0.7437
Epoch 4/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4940 - accuracy: 0.7547 - val_loss: 0.4977 - val_accuracy: 0.7442
Epoch 5/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4923 - accuracy: 0.7573 - val_loss: 0.4979 - val_accuracy: 0.7471
Epoch 6/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4912 - accuracy: 0.7594 - val_loss: 0.4980 - val_accuracy: 0.7515
Epoch 7/100
684/684 [==============================] - 4s 6ms/step - loss: 0.4901 - accuracy: 0.7600 - val_loss: 0.4959 - val_accuracy: 0.7492
Epoch 8/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4891 - accuracy: 0.7606 - val_loss: 0.4953 - val_accuracy: 0.7497
Epoch 9/100
684/684 [==============================] - 3s 5ms/step - loss: 0.4886 - accuracy: 0.7605 - val_loss: 0.4956 - val_accuracy: 0.7492
Epoch 10/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4882 - accuracy: 0.7617 - val_loss: 0.4940 - val_accuracy: 0.7520
Epoch 11/100
684/684 [==============================] - 4s 6ms/step - loss: 0.4875 - accuracy: 0.7614 - val_loss: 0.4954 - val_accuracy: 0.7489
Epoch 12/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4876 - accuracy: 0.7616 - val_loss: 0.4939 - val_accuracy: 0.7484
Epoch 13/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7622 - val_loss: 0.4940 - val_accuracy: 0.7489
Epoch 14/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7626 - val_loss: 0.4954 - val_accuracy: 0.7497
Epoch 15/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4862 - accuracy: 0.7626 - val_loss: 0.4976 - val_accuracy: 0.7489
Epoch 16/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4857 - accuracy: 0.7630 - val_loss: 0.4956 - val_accuracy: 0.7476
Epoch 17/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4861 - accuracy: 0.7625 - val_loss: 0.4953 - val_accuracy: 0.7489
Epoch 18/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4854 - accuracy: 0.7641 - val_loss: 0.4981 - val_accuracy: 0.7476
Epoch 19/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4853 - accuracy: 0.7642 - val_loss: 0.4948 - val_accuracy: 0.7486
Epoch 20/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4846 - accuracy: 0.7632 - val_loss: 0.4979 - val_accuracy: 0.7486
Epoch 21/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7633 - val_loss: 0.4963 - val_accuracy: 0.7502
Epoch 22/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4847 - accuracy: 0.7630 - val_loss: 0.4931 - val_accuracy: 0.7463
Epoch 23/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7627 - val_loss: 0.4945 - val_accuracy: 0.7468
Epoch 24/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4842 - accuracy: 0.7641 - val_loss: 0.4951 - val_accuracy: 0.7497
Epoch 25/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4844 - accuracy: 0.7628 - val_loss: 0.4956 - val_accuracy: 0.7476
Epoch 26/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4843 - accuracy: 0.7633 - val_loss: 0.4950 - val_accuracy: 0.7489
Epoch 27/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7634 - val_loss: 0.4930 - val_accuracy: 0.7494
Epoch 28/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7621 - val_loss: 0.4937 - val_accuracy: 0.7486
Epoch 29/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4841 - accuracy: 0.7639 - val_loss: 0.4929 - val_accuracy: 0.7479
Epoch 30/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4840 - accuracy: 0.7638 - val_loss: 0.4936 - val_accuracy: 0.7492
Epoch 31/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4840 - accuracy: 0.7630 - val_loss: 0.4942 - val_accuracy: 0.7497
Epoch 32/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4836 - accuracy: 0.7640 - val_loss: 0.4949 - val_accuracy: 0.7486
Epoch 33/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4838 - accuracy: 0.7628 - val_loss: 0.4956 - val_accuracy: 0.7497
Epoch 34/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4833 - accuracy: 0.7636 - val_loss: 0.4946 - val_accuracy: 0.7479
Epoch 35/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7652 - val_loss: 0.4953 - val_accuracy: 0.7489
Epoch 36/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7638 - val_loss: 0.4962 - val_accuracy: 0.7517
Epoch 37/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4830 - accuracy: 0.7638 - val_loss: 0.4949 - val_accuracy: 0.7512
Epoch 38/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4831 - accuracy: 0.7640 - val_loss: 0.4941 - val_accuracy: 0.7499
Epoch 39/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7638 - val_loss: 0.4958 - val_accuracy: 0.7479
Epoch 40/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7644 - val_loss: 0.4951 - val_accuracy: 0.7489
Epoch 41/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4829 - accuracy: 0.7632 - val_loss: 0.4954 - val_accuracy: 0.7528
Epoch 42/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4830 - accuracy: 0.7635 - val_loss: 0.4943 - val_accuracy: 0.7471
Epoch 43/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7639 - val_loss: 0.4946 - val_accuracy: 0.7517
Epoch 44/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4828 - accuracy: 0.7635 - val_loss: 0.4957 - val_accuracy: 0.7481
Epoch 45/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7641 - val_loss: 0.4978 - val_accuracy: 0.7484
Epoch 46/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4824 - accuracy: 0.7637 - val_loss: 0.4945 - val_accuracy: 0.7507
Epoch 47/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7646 - val_loss: 0.4989 - val_accuracy: 0.7476
Epoch 48/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4825 - accuracy: 0.7647 - val_loss: 0.4945 - val_accuracy: 0.7481
Epoch 49/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4821 - accuracy: 0.7648 - val_loss: 0.4947 - val_accuracy: 0.7486
Epoch 50/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4822 - accuracy: 0.7644 - val_loss: 0.4948 - val_accuracy: 0.7497
Epoch 51/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4822 - accuracy: 0.7645 - val_loss: 0.4982 - val_accuracy: 0.7440
Epoch 52/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4821 - accuracy: 0.7642 - val_loss: 0.4943 - val_accuracy: 0.7497
Epoch 53/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4820 - accuracy: 0.7643 - val_loss: 0.4961 - val_accuracy: 0.7497
Epoch 54/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4816 - accuracy: 0.7644 - val_loss: 0.4970 - val_accuracy: 0.7494
Epoch 55/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4821 - accuracy: 0.7642 - val_loss: 0.4960 - val_accuracy: 0.7489
Epoch 56/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4820 - accuracy: 0.7649 - val_loss: 0.4945 - val_accuracy: 0.7484
Epoch 57/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4815 - accuracy: 0.7645 - val_loss: 0.4968 - val_accuracy: 0.7479
Epoch 58/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7648 - val_loss: 0.5003 - val_accuracy: 0.7468
Epoch 59/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4818 - accuracy: 0.7655 - val_loss: 0.4951 - val_accuracy: 0.7484
Epoch 60/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4815 - accuracy: 0.7646 - val_loss: 0.4948 - val_accuracy: 0.7481
Epoch 61/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7652 - val_loss: 0.4981 - val_accuracy: 0.7471
Epoch 62/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4810 - accuracy: 0.7657 - val_loss: 0.4946 - val_accuracy: 0.7481
Epoch 63/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4811 - accuracy: 0.7653 - val_loss: 0.4957 - val_accuracy: 0.7481
Epoch 64/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4805 - accuracy: 0.7657 - val_loss: 0.4947 - val_accuracy: 0.7460
Epoch 65/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7646 - val_loss: 0.4953 - val_accuracy: 0.7466
Epoch 66/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7648 - val_loss: 0.4953 - val_accuracy: 0.7450
Epoch 67/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7646 - val_loss: 0.4950 - val_accuracy: 0.7502
Epoch 68/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7653 - val_loss: 0.4997 - val_accuracy: 0.7460
Epoch 69/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4806 - accuracy: 0.7641 - val_loss: 0.4983 - val_accuracy: 0.7463
Epoch 70/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4812 - accuracy: 0.7659 - val_loss: 0.4949 - val_accuracy: 0.7497
Epoch 71/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4812 - accuracy: 0.7665 - val_loss: 0.4951 - val_accuracy: 0.7512
Epoch 72/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4807 - accuracy: 0.7650 - val_loss: 0.4965 - val_accuracy: 0.7481
Epoch 73/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7657 - val_loss: 0.4980 - val_accuracy: 0.7471
Epoch 74/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7654 - val_loss: 0.4948 - val_accuracy: 0.7492
Epoch 75/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4809 - accuracy: 0.7642 - val_loss: 0.4951 - val_accuracy: 0.7494
Epoch 76/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4809 - accuracy: 0.7654 - val_loss: 0.4971 - val_accuracy: 0.7476
Epoch 77/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4805 - accuracy: 0.7657 - val_loss: 0.4958 - val_accuracy: 0.7492
Epoch 78/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4803 - accuracy: 0.7654 - val_loss: 0.4956 - val_accuracy: 0.7473
Epoch 79/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4806 - accuracy: 0.7655 - val_loss: 0.4951 - val_accuracy: 0.7486
Epoch 80/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7660 - val_loss: 0.4969 - val_accuracy: 0.7476
Epoch 81/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4802 - accuracy: 0.7654 - val_loss: 0.4948 - val_accuracy: 0.7494
Epoch 82/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4802 - accuracy: 0.7666 - val_loss: 0.4967 - val_accuracy: 0.7538
Epoch 83/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7657 - val_loss: 0.4957 - val_accuracy: 0.7497
Epoch 84/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4801 - accuracy: 0.7658 - val_loss: 0.5001 - val_accuracy: 0.7463
Epoch 85/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4806 - accuracy: 0.7649 - val_loss: 0.4955 - val_accuracy: 0.7497
Epoch 86/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4801 - accuracy: 0.7664 - val_loss: 0.4945 - val_accuracy: 0.7492
Epoch 87/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4800 - accuracy: 0.7652 - val_loss: 0.4946 - val_accuracy: 0.7520
Epoch 88/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4797 - accuracy: 0.7660 - val_loss: 0.5003 - val_accuracy: 0.7489
Epoch 89/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7663 - val_loss: 0.4957 - val_accuracy: 0.7492
Epoch 90/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7646 - val_loss: 0.4950 - val_accuracy: 0.7523
Epoch 91/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4800 - accuracy: 0.7664 - val_loss: 0.4966 - val_accuracy: 0.7502
Epoch 92/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4799 - accuracy: 0.7648 - val_loss: 0.4967 - val_accuracy: 0.7510
Epoch 93/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4795 - accuracy: 0.7669 - val_loss: 0.4971 - val_accuracy: 0.7473
Epoch 94/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4800 - accuracy: 0.7657 - val_loss: 0.4982 - val_accuracy: 0.7476
Epoch 95/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4801 - accuracy: 0.7657 - val_loss: 0.4947 - val_accuracy: 0.7520
Epoch 96/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4797 - accuracy: 0.7658 - val_loss: 0.4977 - val_accuracy: 0.7484
Epoch 97/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4798 - accuracy: 0.7667 - val_loss: 0.4983 - val_accuracy: 0.7499
Epoch 98/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4794 - accuracy: 0.7670 - val_loss: 0.4957 - val_accuracy: 0.7479
Epoch 99/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4793 - accuracy: 0.7660 - val_loss: 0.4945 - val_accuracy: 0.7502
Epoch 100/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7659 - val_loss: 0.4952 - val_accuracy: 0.7507

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.4956 - accuracy: 0.7515 - 337ms/epoch - 1ms/step
Loss: 0.4956136643886566, Accuracy: 0.7514868974685669

In [ ]:
from google.colab import files

# Export our model to HDF5 file
nn.save('/content/AlphabetSoupCharityOptimized.h5')
files.download('/content/AlphabetSoupCharityOptimized.h5')